name: CI / CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
#    uses: ./.github/workflows/integration-tests.yml
    - run: echo hi

  build-and-push:
    if: github.ref == 'refs/heads/main'
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-and-deploy.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
